### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by xuanbachle** [codeflaws/codeflaws#2]
When I run Angelix with your provided script. The following error happened.

====
+++ Running angelix with defect Group 1, group size = 1
Traceback (most recent call last):
  File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
PermissionError: [Errno 13] Permission denied: 'my_outputinput-neg1'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bach/workspace/repairtools/angelix/src/repair/main.py", line 528, in <module>
    shutil.rmtree(working_dir, onerror=rm_force)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 412, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bach/workspace/repairtools/angelix/src/repair/main.py", line 524, in rm_force
    shutil.rmtree(name)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree

Traceback (most recent call last):
  File "/home/bach/workspace/repairtools/angelix/src/repair/main.py", line 528, in <module>
    shutil.rmtree(working_dir, onerror=rm_force)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 412, in _rmtree_safe_fd
    _rmtree_safe_fd(dirfd, fullname, onerror)
  File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/home/bach/workspace/repairtools/angelix/src/repair/main.py", line 524, in rm_force
    shutil.rmtree(name)
  File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.5/shutil.py", line 396, in _rmtree_safe_fd
    onerror(os.listdir, path, sys.exc_info())
  File "/usr/lib/python3.5/shutil.py", line 393, in _rmtree_safe_fd
    names = os.listdir(topfd)
NotADirectoryError: [Errno 20] Not a directory: '/home/bach/workspace/emsedata/script/codeflaws/all-script/angelix-experiments/.angelix/frontend/my_outputinput-neg1'
====

Am I doing something wrong?

Bests,

**Comment by mechtaev** [comment]
@xuanbachle, could you please try to add 

`os.chmod(name, stat.S_IWRITE)`

at [this](https://github.com/mechtaev/angelix/blob/master/src/repair/main.py#L523) location and tell if it helps? If it doesn't, can you describe how to reproduce this bug?

**Comment by xuanbachle** [comment]
Thanks Sergey.

I added the code above to the line you suggested, but it didn't work...
I tried running the script by:
bash run-version-angelix.sh test.txt
where the test.txt contains:
476-A-bug-16066033-16066045

**Comment by stan6** [comment]
@xuanbachle. I am not able to reproduce your error. 

There may be two possible reasons where things could go wrong:

1. The angelix-experiments directory ($angelixexperimentsdir) should be different from the location of the directory ($versiondir) in which you untar the codeflaws.tar.gz to avoid removing the content of the tar file. 

1. Can please find and show this line from the execution log? ```angelix /home/ubuntu/all/codeflaws/all-script/angelix-run-2017-06-06-17-02-48/476-A-bug-16066033-16066045/476-A-16066033-buggy 476-A-16066033.c /home/ubuntu/all/codeflaws/all-script/angelix-run-2017-06-06-17-02-48/476-A-bug-16066033-16066045/476-A-16066033-buggy/test-angelix.sh p1 p2 n1 --golden /home/ubuntu/all/codeflaws/all-script/angelix-run-2017-06-06-17-02-48/476-A-bug-16066033-16066045/476-A-16066045-golden --localize-from-bottom --defect if-conditions loop-conditions assignments --synthesis-levels alternatives variables extended-arithmetic extended-logic extended-inequalities mixed-conditional conditional-arithmetic --timeout 3600 --group-size 1 --synthesis-global-vars --synthesis-func-params --synthesis-used-vars --klee-solver-timeout 20 --klee-timeout 300 --klee-max-forks 500 --synthesis-timeout 100000 --configure 'make clean'```
